### ISSUE TITLE
Run comparison tests to verify the same results are produced

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#134]
Run comparison tests to verify the same results are produced from the WRIMS v2.2 installer produced from the automated build system and the WRIMS v2.2 installer produced on Hao Xie’s machine.

**Comment by rma-tom** [comment]
@hxiedwr -- Please advise as to who in addition to yourself should be part of the discussion about automated comparison tests. 

We discussed this a little in the meeting last week, and need to make some decisions about what we're going to test and when we do the tests. The proof-of-concept we did in April ran a CalLite model for a period from 1921 to 2015. It takes about 30-40 minutes to run on my computer. The model and a set of old results to compare to are drawn from a zipfile in GitHub Artifacts [ https://github.com/CentralValleyModeling/wrims/packages/2124640 ] 

The questions we need to address are:

1. When do we want to trigger this compute comparison?
2. What models to we want to use for the tests?

These are rather complicated questions, so I'm really trying to start a discussion here and not asking for a hard answer right now.

**Comment by hxiedwr** [comment]
@dwr-ycheng @dwr-zroy I don't know what resources we have for the testing and if the testing plan we have is overlapped with what Tom planed to do.

Personally I prefer manual testing instead of auto testing. I think the testing plan we have focus on manual testing.

**Comment by hxiedwr** [comment]
Also I think RMA just need to have the package conceptually work and share with us. We can thoroughly test and dig into all the functions in WRIMS core and gui.

**Comment by rma-tom** [comment]
The proof-of-concept test that we put together in April ran successfully for me today on the branch I created for the issues relating to DSS6 and DSS7 display problems. I was mistaken about the time window for the test run. It appears that we limited the test run to 1921-1925, and it runs in under 10 minutes in a container on GitHub.

https://github.com/CentralValleyModeling/wrims/actions/runs/11963782045

A superficial comparison of the report generated today and the one generated in April suggests that todays results are the same as April's and the merge from the main development branch didn't affect compute results

**Comment by hxiedwr** [comment]
Great!

**Comment by jmdegeorge** [comment]
I reviewed Tom's current process for the WRIMS Compute (Automated Test) action and I believe this is good strategy going forward. 

We currently have 1 working compute test Action in github that can be triggered manually against any branch whenever we want it to. It currently takes approximately 8min to complete, but to keep the github resource usage down it make sense to only run it as needed. We can continue to add additional compute test workflows (Actions) as we continue to develop WRIMS. 

It may be worth extracting the generation of a full WRIMS installer into a separate github Workflow Action as well that we can run manually as needed, if we don't want to trigger an installer build on every commit. 

![image](https://github.com/user-attachments/assets/fbae9c62-2049-44e3-b51f-979840757045)

**Comment by dwr-zroy** [comment]
Love it. I think this is great as a "end of the line" integration test.

One thought: I think that the partial CalSim run that WRIMS uses here will be perpetually "out of date". I don't think it makes sense to try and "chase down" the latest release of CalSim every time we want to run this test. With that in mind, here is the issue I see: those "cutting edge" CalSim models are likely to be what most users are focusing on when they update their versions of WRIMS. 

In my mind, manual testing with the latest CalSim models is essential because if WRIMS doesn't behave exactly as expected there it's going to be immediately obvious by the heavy users. Is users are the first to find those differences, it might erode trust in the QA/QC process. That might make it hard to get folks to update in the future.

I'm sure these thoughts aren't new to you all, but I wanted to make sure it was said here.

**Comment by jmdegeorge** [comment]
Thanks for the input @dwr-zroy! I completely agree some level of manual testing should always be involved when testing a release candidate before making it available to the public. 

How long is the lifespan on the "latest CalSim models" you mentioned? And how frequently are they updated?

**Comment by dwr-zroy** [comment]
Good question. Updating & Maintaining CalSim and CalLite is what the Applications team (multiple DWR staff) does every day. 

That being said, here is my back of the envelope frequency estimate:
- Public releases of CalSim (think "new book release"):
    - timing varies, but different projects probably release approx. quarterly.
- Internal releases which require internal QA/QC (think "draft for an editor"): 
    - anywhere from weekly to monthly across all parallel projects.
- Bug Fixes, Working Drafts, or Sensitivity Analyses (think "authors draft"): 
    - during projects, this happens daily. 

The automatic process can probably target that public release level (that might even be too often, because of the large model input files that change with every public release). However, the manual process would be able to target that internal release, or even some of those working draft versions if needed.

**Comment by rma-tom** [comment]
As things stand, the comparison test runs only when manually triggered, and only runs one CalLite comparison test for a 10-year abbreviated period of record. Is this good for our purposes, or should we provide new tests or code to run them?

We could, for example, create a github workflow to force the present test to run when a tagged build is created. We could also create a more extensive test and comparison report template to be run for actual releases.

Essentially, I'm asking if DWR want any additional work to be done on this issue, of the present state of this comparison test is adequate to present needs?

**Comment by hxiedwr** [comment]
To me, it seems that we don't need additional efforts for this issue.

**Comment by dwr-zroy** [comment]
Agreed, we are in a great place today.

We can always add the additional workflows, or expand on the comparison report in the future. If there is a place to track those "ideas" or "features", we should track them there.

**Comment by rma-tom** [comment]
There's already a discussion on this topic here
https://github.com/CentralValleyModeling/wrims/discussions/63
I will place a link to this issue in a comment there and close this issue
