### ISSUE TITLE
Determine comparison tool to use for automated testing

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#56]
Determine comparison tool to use for automated testing.

In #54, @rma-tom used JUnit to run DSS Compare of results from running CalSim studies using wrimsv2 vs wrims-core. @rma-psmorris recommended considering other options aside from JUnit.

Possible options:
- CalLite Report Tool (already included wrimsv2)
- EPPT
- Data Analysis Tab in EPPT (integrated CalLite Report Tool)
- DSS Excel Plug-in

**Comment by hxiedwr** [comment]
The Report Tool is for both CalSim and CalLite.

Right now, I think the Report Tool neither in WRIMS 2 nor EPPT works because Report Tool needs Vista, which doesn't support HecLib 7.

Since we are working on the WRIMS DevOps project, I would suggest fix the Report Tool in WRIMS 2 so it works with HecLib 7 without the usage of Vista.




________________________________
From: dezidizon ***@***.***>
Sent: Wednesday, February 28, 2024 9:50 AM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CentralValleyModeling/wrims] Determine comparison tool to use for automated testing (Issue #56)


Determine comparison tool to use for automated testing.

In #54<https://github.com/CentralValleyModeling/wrims/issues/54>, @rma-tom<https://github.com/rma-tom> used JUnit to run DSS Compare of results from running CalSim studies using wrimsv2 vs wrims-core. @rma-psmorris<https://github.com/rma-psmorris> recommended considering other options aside from JUnit.

Possible options:

  *   CalLite Report Tool (already included wrimsv2)
  *   EPPT
  *   Data Analysis Tab in EPPT (integrated CalLite Report Tool)
  *   DSS Excel Plug-in

**Comment by rma-tom** [comment]
Will add a simple -- non-configurable -- comparison report to the prototype created under issue #54

**Comment by dezidizon** [comment]
Decision was made that the CalLite Report Tool will be used. Refer to #60 and #61 for further progress
